"""empty message

Revision ID: 2692e967fa52
Revises: f7cb781513ae
Create Date: 2024-05-01 08:21:30.444870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2692e967fa52'
down_revision = 'f7cb781513ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_introvert', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('is_grandparent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_grandparent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.drop_column('is_introvert')

    # ### end Alembic commands ###
